name: Manual test matrix
on: push

jobs:
  test-container:
    strategy:
      fail-fast: false
      matrix:
        container-runs-on:
          - alpine
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container-runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
