name: Test matrix
on:
  push:
    branches: [test]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: dscho/action-tmate@test
        with:
          limit-access-to-actor: true
