name: Test matrix
on:
  push:
    branches: [test]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-10.15
          - macos-11.0
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: dscho/action-tmate@test
        with:
          limit-access-to-actor: true
